---
slug: go_basics_softcover_book
filename: go_basics_softcover_book
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2021
uuid: 4ade11b7-7975-4588-9e90-df90d1bfc7f4
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
